---
title: "Figure 1"
author: "Carolina Lobato"
date: "2024-08-10"
output: html_document
---

# Load Libraries
```{r loadlib, include = F}
library(phyloseq)
library(tidyverse)
```

# Import data
```{r}
load("outputs/r/2_setup/bh-pb.RData") # 419 taxa and 132 samples
load("outputs/r/2_setup/taxo-pb.RData") # taxo.pb
load("outputs/r/2_setup/c100.RData") # c100
```

# Plot A: Itol
## Get data
```{r}
# Get PB sequences
ref_seq_pb <- refseq(bh_pb)
asv_ids_pb <- taxa_names(bh_pb)
asv_seq_pb <- data.frame(
    db_pb = asv_ids_pb,
    Sequence = as.character(ref_seq_pb[asv_ids_pb]),
    Length = Biostrings::width(ref_seq_pb[asv_ids_pb]))

asv_seq_pb_taxo <- merge(asv_seq_pb, taxo.pb, by = "db_pb") %>%
  select(db_pb, Sequence) %>%
  write_csv("data/megax/bh_pb.fasta")

# Get PB taxonomy
write.csv(taxo.pb, file = "data/itol/bh_pb/bh_pb-tax.csv")

# c100_99_all <- c100 %>% filter(id > 99) %>% # 378
#   group_by(db_pb) %>% summarize(count = n())

# Get matches >99%
c100_pb <- c100 %>% 
  select(q_amplicon, db_pb, id) %>% 
  mutate(type = ifelse(id <= 85.93, "[77.35, 85.93]", 
                       ifelse(id <= 87.95, "(85.93, 87.95]",
                              ifelse(id <= 90.1, "(87.95, 90.1]",
                                     ifelse(id <= 92.9, "(90.1, 92.9]",
                                            ifelse(id <= 96.55, "(92.9, 96.55]",
                                                   ifelse(id <= 99, "(96.55, 99]",
                                                         "(99, 100]"))))))) %>%
  mutate(type = factor(type, levels = rev(c("(99, 100]", "(96.55, 99]", "(92.9, 96.55]", "(90.1, 92.9]",                                          "(87.95, 90.1]", "(85.93, 87.95]", "[77.35, 85.93]")))) %>%
  group_by(db_pb) %>%
  slice_max(n = 1, order_by = type, with_ties = T) %>%
  ungroup() # 3817 assignments

unique_pb <- c100_pb %>% select(db_pb) %>% unique() # 419 pb ASVs
unique_amp <- c100_pb %>% select(q_amplicon) %>% unique() # 348 amplicon ASVs

unique_amp_type <- c100_pb %>% group_by(type) %>% summarize(n = n_distinct(q_amplicon)); unique_amp_type
sum(unique_amp_type$n) # 359

unique_pb_type <- c100_pb %>% group_by(type) %>% summarize(n = n_distinct(db_pb)); unique_amp_type
sum(unique_pb_type$n) # 419

# How many amplicon ASVs per Pb ASV
c100_99 <- c100_pb %>% filter(id > 99) %>% 
  group_by(db_pb) %>% summarize(count = n()) %>% 
  write_csv("data/itol/bh_pb-asgn.csv") # 379

c100_99_all == c100_99

sum(c100_99$count) # 3701 assignments
unique_pb99 <- c100_99 %>% select(db_pb) %>% unique() #378 ASVs

# How many Pb ASVs per amplicon ASV
unique_amp99 <- c100_pb %>% filter(id > 99) %>%  #filter(type == ">99") %>% #
  group_by(q_amplicon) %>% summarize(count = n()) #335

# Get Genus
genus.pb <- taxo.pb %>% select(Genus) %>% unique() %>% write_csv("data/itol/bh_pb/bh_pb-genus.csv")

genus.stat <- taxo.pb %>% group_by(Genus) %>% summarize(count = n())
class.stat <- taxo.pb %>% group_by(Class) %>% summarize(count = n())
```

## Import tree and anotate
```{r}
Fig1 <- grid::rasterGrob(png::readPNG("outputs/r/Fig_1/pb_tree.png"), interpolate = T)

# Add legend
Class <- c("Actinobacteria", "Alphaproteobacteria", "Bacilli", "Bacteroidia", "Gammaproteobacteria")
color.class <- rev(c("#98cc90","#563C5C","#5197c5","#d8cd99","#8A4D30"))

legend <- cowplot::get_legend(
  ggplot(data.frame(x = factor(1:5), y = 1:5)) +
  geom_tile(aes(x = x, y = y, fill = x)) +
  scale_fill_manual(name = "Class", values = color.class, 
                    labels = Class) +
  theme_classic() +
  theme(legend.direction = "horizontal",
        legend.text = element_text(size = 6),
        legend.title = element_text(size = 8),
        legend.key.size = unit(0.25, "cm"),
        legend.key.spacing.x = unit(1, "lines"),
        legend.box.margin = margin(0,0,0,0, "cm"),
        legend.box.spacing = unit(0, "lines"),
        legend.spacing = unit(0, "lines"),
        legend.background = element_rect(fill = "transparent", color = "transparent")))

Fig1l <- cowplot::plot_grid(Fig1, ncol = 1) + 
  theme(plot.margin = margin(0.25, -5, 1, -5, "cm")) +
  annotation_custom(legend, 
                    xmin = 0, xmax = 1,
                    ymin = -0.06, ymax = -0.06); Fig1l

# save(Fig1l, file = "outputs/r/Fig_1/pb_tree_lg.RData")

load("/home/jmachadofreitas/Projects/culturing-seed-bacteria/outputs/r/Fig_1/pb_tree_lg.RData") #Fig1l

# Add Genera
pos.x <- c(0.041, 0.038, 0.047, 0.053, #1
           0.058, 0.068, 0.070, 0.066, 0.081,#2
           0.081, 0.092, 0.096, 0.112, #3
           0.113, 0.205, 0.375, 0.410, #4
           0.425, 0.530, 0.613, 0.618, #5
           0.615, 0.616, 0.625, 0.627, #6
           0.630, 0.627, 0.633, 0.623, #7
           0.619, 0.587, 0.491, 0.470, #8
           0.442, 0.400, 0.360, 0.314, #9
           0.220, 0.040)

pos.y <- c(0.768, 0.783, 0.795, 0.806, #1
           0.815, 0.822, 0.830, 0.839, 0.848, #2
           0.858, 0.868, 0.879, 0.890, #3
           0.900, 0.966, 0.982, 0.970, #4
           0.961, 0.860, 0.684, 0.668, #5
           0.657, 0.645, 0.625, 0.615, #6
           0.590, 0.564, 0.551, 0.538, #7
           0.513, 0.320, 0.172, 0.160, #8
           0.138, 0.117, 0.105, 0.101, #9
           0.113, 0.335)

label <- c("Pedobacter","Sphingobacterium","Aeromicrobium","Arthrobacter", #1
           "Micrococcus","Rothia","Kocuria","Brevibacterium", "Kocuria",#2
           "Curtobacterium","Rathayibacter","Frigobacterium","Agreia", #3
           "Microbacterium","Paenibacillus","Brevibacillus","Enterococcus", #4
           "Oceanobacillus","Bacillus","Sphingomonas","Phyllobacterium", #5
           "Paracoccus","Rhizobium","Brevundimonas","Bradyrhizobium", #6
           "Methylobacterium","Xanthomonas","Stenotrophomonas","Ralstonia", #7
           "Massilia","Pseudomonas","Enhydrobacter","Erwinia", #8
           "Pantoea","Enterobacter","Klebsiella","Enterobacter", #9
           "Escherichia-Shingella","Pantoea") #10

Fig1lg <- cowplot::plot_grid(Fig1l, 
                             label_size = 12,
                             greedy = T,
                             nrow = 1) + 
  geom_text(aes(x = pos.x * 0.88 + 0.225,
                y = pos.y * 1.075 - 0.065),
            label = label,
            fontface = "italic",
            size = 2) + 
  theme(plot.margin = margin(0, -3, 0.25, -3, "cm")) #; Fig1lg

cowplot::save_plot(
  plot = Fig1lg,
  "/home/jmachadofreitas/Projects/culturing-seed-bacteria/outputs/r/Fig_1/fig1-final2.png",
  base_width = 27,
  base_height = 18,
  units = "cm",
  bg =  "white",
  scale = 1,
  dpi = 600)
```